on: [push, pull_request]
name: Test
jobs:
  test:
    # strategy:
      # matrix:
        # go-version: [1.16.x, 1.17.x]
        # os: [ubuntu-latest, macos-latest, windows-latest]
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        # go-version: ${{ matrix.go-version }}
        go-version: 1.17
    - uses: actions/checkout@v3
    - run: go test ./...